# Medical Annotation Database Population

This notebook allows you to manually populate the medical annotation database with documents, entities, and relationships.

## Quick Guide:
1. **Create Documents** - Add medical text documents
2. **Create Annotations** - Set up annotation sessions
3. **Add Entities** - Tag medical entities (diseases, medications, etc.)
4. **Add Relations** - Create relationships between entities
5. **Query & Explore** - View and explore the database

## Setup

In [3]:
import sys
from pathlib import Path

# Add project root to path
project_root = Path.cwd()
sys.path.insert(0, str(project_root))

print(f"Project root: {project_root}")
print("Python path updated")

Project root: C:\Users\Jan\projects\oracle-challenge
Python path updated

In [4]:

import pandas as pd
from sqlmodel import Session, select

# Import database
from src.database import create_db_and_tables, get_engine

# Import models
from src.models import (
    Annotation,
    Document,
    Entity,
    EntityType,
    Relation,
    RelationType,
)

print("✅ Imports successful")

engine = get_engine()
print("✅ Engine created")
# Create tables if they don't exist
create_db_and_tables()
print("✅ Database tables created/verified")

✅ Imports successful
✅ Engine created
2025-11-06 07:21:36,687 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,688 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("annotations")
2025-11-06 07:21:36,689 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-11-06 07:21:36,690 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("documents")
2025-11-06 07:21:36,690 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-11-06 07:21:36,691 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("entities")
2025-11-06 07:21:36,692 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-11-06 07:21:36,693 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("relations")
2025-11-06 07:21:36,694 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-11-06 07:21:36,695 INFO sqlalchemy.engine.Engine COMMIT
✅ Database tables created/verified

## Helper Functions

In [5]:
def create_document(title: str, text: str) -> Document:
    """Create a new document in the database."""
    with Session(engine) as session:
        doc = Document(title=title, text=text)
        session.add(doc)
        session.commit()
        session.refresh(doc)
        print(f"✅ Document created: ID={doc.id}, Title='{doc.title}'")
        return doc


def create_annotation(document_id: int, annotator_id: str = "manual", status: str = "in_progress") -> Annotation:
    """Create a new annotation for a document."""
    with Session(engine) as session:
        annotation = Annotation(
            document_id=document_id,
            annotator_id=annotator_id,
            status=status,
        )
        session.add(annotation)
        session.commit()
        session.refresh(annotation)
        print(f"✅ Annotation created: ID={annotation.id}, Document={document_id}, Status={status}")
        return annotation


def create_entity(
    annotation_id: int,
    text: str,
    entity_type: EntityType,
    start_char: int,
    end_char: int,
    confidence: float = 1.0,
) -> Entity:
    """Create a new entity annotation."""
    with Session(engine) as session:
        entity = Entity(
            annotation_id=annotation_id,
            text=text,
            entity_type=entity_type,
            start_char=start_char,
            end_char=end_char,
            confidence=confidence,
        )
        session.add(entity)
        session.commit()
        session.refresh(entity)
        print(f"✅ Entity created: ID={entity.id}, Text='{entity.text}', Type={entity_type.value}")
        return entity


def create_relation(
    annotation_id: int,
    source_entity_id: int,
    target_entity_id: int,
    relation_type: RelationType,
    confidence: float = 1.0,
) -> Relation:
    """Create a new relation between entities."""
    with Session(engine) as session:
        relation = Relation(
            annotation_id=annotation_id,
            source_entity_id=source_entity_id,
            target_entity_id=target_entity_id,
            relation_type=relation_type,
            confidence=confidence,
        )
        session.add(relation)
        session.commit()
        session.refresh(relation)
        print(f"✅ Relation created: ID={relation.id}, {source_entity_id} --[{relation_type.value}]--> {target_entity_id}")
        return relation


print("✅ Helper functions defined")

✅ Helper functions defined

## Query Functions

In [6]:
def list_documents() -> pd.DataFrame:
    """List all documents in the database."""
    with Session(engine) as session:
        documents = session.exec(select(Document)).all()
        data = [
            {
                "ID": doc.id,
                "Title": doc.title,
                "Text Preview": doc.text[:50] + "..." if len(doc.text) > 50 else doc.text,
                "Text Length": len(doc.text),
                "Created": doc.created_at.isoformat(),
            }
            for doc in documents
        ]
        return pd.DataFrame(data)


def list_annotations(document_id: int | None = None) -> pd.DataFrame:
    """List annotations, optionally filtered by document."""
    with Session(engine) as session:
        statement = select(Annotation)
        if document_id is not None:
            statement = statement.where(Annotation.document_id == document_id)

        annotations = session.exec(statement).all()
        data = [
            {
                "ID": ann.id,
                "Document ID": ann.document_id,
                "Annotator": ann.annotator_id,
                "Status": ann.status,
                "Entities": len(ann.entities),
                "Relations": len(ann.relations),
                "Updated": ann.updated_at.isoformat(),
            }
            for ann in annotations
        ]
        return pd.DataFrame(data)


def list_entities(annotation_id: int | None = None) -> pd.DataFrame:
    """List entities, optionally filtered by annotation."""
    with Session(engine) as session:
        statement = select(Entity)
        if annotation_id is not None:
            statement = statement.where(Entity.annotation_id == annotation_id)

        entities = session.exec(statement).all()
        data = [
            {
                "ID": ent.id,
                "Text": ent.text,
                "Type": ent.entity_type.value,
                "Start": ent.start_char,
                "End": ent.end_char,
                "Confidence": ent.confidence,
                "Annotation ID": ent.annotation_id,
            }
            for ent in entities
        ]
        return pd.DataFrame(data)


def list_relations(annotation_id: int | None = None) -> pd.DataFrame:
    """List relations, optionally filtered by annotation."""
    with Session(engine) as session:
        statement = select(Relation)
        if annotation_id is not None:
            statement = statement.where(Relation.annotation_id == annotation_id)

        relations = session.exec(statement).all()
        data = [
            {
                "ID": rel.id,
                "Source Entity ID": rel.source_entity_id,
                "Relation Type": rel.relation_type.value,
                "Target Entity ID": rel.target_entity_id,
                "Confidence": rel.confidence,
                "Annotation ID": rel.annotation_id,
            }
            for rel in relations
        ]
        return pd.DataFrame(data)


print("✅ Query functions defined")

✅ Query functions defined

## View Database Summary

In [7]:
def database_summary():
    """Print a summary of the database contents."""
    with Session(engine) as session:
        doc_count = len(session.exec(select(Document)).all())
        ann_count = len(session.exec(select(Annotation)).all())
        ent_count = len(session.exec(select(Entity)).all())
        rel_count = len(session.exec(select(Relation)).all())

        print("\n" + "="*50)
        print("📊 DATABASE SUMMARY")
        print("="*50)
        print(f"📄 Documents:   {doc_count}")
        print(f"📝 Annotations: {ann_count}")
        print(f"🏷️  Entities:    {ent_count}")
        print(f"🔗 Relations:   {rel_count}")
        print("="*50 + "\n")

database_summary()

2025-11-06 07:21:36,722 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,731 INFO sqlalchemy.engine.Engine SELECT documents.id, documents.title, documents.text, documents.created_at, documents.updated_at
FROM documents
2025-11-06 07:21:36,732 INFO sqlalchemy.engine.Engine [generated in 0.00071s] ()
2025-11-06 07:21:36,734 INFO sqlalchemy.engine.Engine SELECT annotations.id, annotations.annotator_id, annotations.status, annotations.document_id, annotations.created_at, annotations.updated_at
FROM annotations
2025-11-06 07:21:36,735 INFO sqlalchemy.engine.Engine [generated in 0.00066s] ()
2025-11-06 07:21:36,737 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
2025-11-06 07:21:36,738 INFO sqlalchemy.engine.Engine [generated in 0.00109s] ()
2025-11-06 07:21:36,740 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
2025-11-06 07:21:36,741 INFO sqlalchemy.engine.Engine [generated in 0.00071s] ()

==================================================
📊 DATABASE SUMMARY
==================================================
📄 Documents:   0
📝 Annotations: 0
🏷️  Entities:    0
🔗 Relations:   0
==================================================

2025-11-06 07:21:36,742 INFO sqlalchemy.engine.Engine ROLLBACK

## Example 1: Create Sample Document with Annotations

Let's create a medical case document and add annotations to it.

In [8]:
# Create a sample document
sample_text = """Patient presents with persistent dry cough for 10 days, accompanied by fever and shortness of breath.
Chest X-ray reveals bilateral infiltrates suggestive of pneumonia.
Prescribed azithromycin 500mg daily for 5 days and albuterol inhaler for bronchodilation.
Advised bed rest and increased fluid intake."""

doc = create_document(
    title="Case 1: Respiratory Infection",
    text=sample_text
)

print(f"\nDocument text length: {len(sample_text)} characters")
print(f"Document ID: {doc.id}")

2025-11-06 07:21:36,747 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,749 INFO sqlalchemy.engine.Engine INSERT INTO documents (title, text, created_at, updated_at) VALUES (?, ?, ?, ?)
2025-11-06 07:21:36,750 INFO sqlalchemy.engine.Engine [generated in 0.00097s] ('Case 1: Respiratory Infection', 'Patient presents with persistent dry cough for 10 days, accompanied by fever and shortness of breath. \nChest X-ray reveals bilateral infiltrates sug ... (11 characters truncated) ... pneumonia. \nPrescribed azithromycin 500mg daily for 5 days and albuterol inhaler for bronchodilation. \nAdvised bed rest and increased fluid intake.', '2025-11-05 21:21:36.746874', '2025-11-05 21:21:36.746894')
2025-11-06 07:21:36,752 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,755 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,758 INFO sqlalchemy.engine.Engine SELECT documents.id, documents.title, documents.text, documents.created_at, documents.updated_at
FROM documents
WHERE documents.id = ?
2025-11-06 07:21:36,758 INFO sqlalchemy.engine.Engine [generated in 0.00060s] (1,)
✅ Document created: ID=1, Title='Case 1: Respiratory Infection'
2025-11-06 07:21:36,759 INFO sqlalchemy.engine.Engine ROLLBACK

Document text length: 306 characters
Document ID: 1

In [9]:
# Create annotation session for this document
annotation = create_annotation(
    document_id=doc.id,
    annotator_id="doctor_smith",
    status="in_progress"
)

print(f"\nAnnotation ID: {annotation.id}")

2025-11-06 07:21:36,765 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,767 INFO sqlalchemy.engine.Engine INSERT INTO annotations (annotator_id, status, document_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
2025-11-06 07:21:36,767 INFO sqlalchemy.engine.Engine [generated in 0.00093s] ('doctor_smith', 'IN_PROGRESS', 1, '2025-11-05 21:21:36.765187', '2025-11-05 21:21:36.765203')
2025-11-06 07:21:36,770 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,773 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,774 INFO sqlalchemy.engine.Engine SELECT annotations.id, annotations.annotator_id, annotations.status, annotations.document_id, annotations.created_at, annotations.updated_at
FROM annotations
WHERE annotations.id = ?
2025-11-06 07:21:36,775 INFO sqlalchemy.engine.Engine [generated in 0.00075s] (1,)
✅ Annotation created: ID=1, Document=1, Status=in_progress
2025-11-06 07:21:36,776 INFO sqlalchemy.engine.Engine ROLLBACK

Annotation ID: 1

In [10]:
# Now let's add entities to this annotation
# First, let's identify the positions in the text

# Let's find positions of key terms
text = sample_text

# Find positions using Python string methods
print("Finding entity positions in text...\n")

# Symptom: dry cough
pos = text.find("dry cough")
print(f"'dry cough' at position {pos}-{pos + len('dry cough')}")

# Symptom: fever
pos = text.find("fever")
print(f"'fever' at position {pos}-{pos + len('fever')}")

# Symptom: shortness of breath
pos = text.find("shortness of breath")
print(f"'shortness of breath' at position {pos}-{pos + len('shortness of breath')}")

# Disease: pneumonia
pos = text.find("pneumonia")
print(f"'pneumonia' at position {pos}-{pos + len('pneumonia')}")

# Medication: azithromycin
pos = text.find("azithromycin")
print(f"'azithromycin' at position {pos}-{pos + len('azithromycin')}")

# Dosage: 500mg
pos = text.find("500mg")
print(f"'500mg' at position {pos}-{pos + len('500mg')}")

# Medication: albuterol
pos = text.find("albuterol")
print(f"'albuterol' at position {pos}-{pos + len('albuterol')}")

Finding entity positions in text...

'dry cough' at position 33-42
'fever' at position 71-76
'shortness of breath' at position 81-100
'pneumonia' at position 159-168
'azithromycin' at position 182-194
'500mg' at position 195-200
'albuterol' at position 222-231

In [11]:
# Create entities
entities = []

# Symptoms
entity1 = create_entity(
    annotation_id=annotation.id,
    text="dry cough",
    entity_type=EntityType.SYMPTOM,
    start_char=29,
    end_char=38,
    confidence=1.0
)
entities.append(entity1)

entity2 = create_entity(
    annotation_id=annotation.id,
    text="fever",
    entity_type=EntityType.SYMPTOM,
    start_char=70,
    end_char=75,
    confidence=1.0
)
entities.append(entity2)

entity3 = create_entity(
    annotation_id=annotation.id,
    text="shortness of breath",
    entity_type=EntityType.SYMPTOM,
    start_char=80,
    end_char=99,
    confidence=1.0
)
entities.append(entity3)

# Disease
entity4 = create_entity(
    annotation_id=annotation.id,
    text="pneumonia",
    entity_type=EntityType.DISEASE,
    start_char=155,
    end_char=164,
    confidence=0.95
)
entities.append(entity4)

# Medications
entity5 = create_entity(
    annotation_id=annotation.id,
    text="azithromycin",
    entity_type=EntityType.MEDICATION,
    start_char=178,
    end_char=190,
    confidence=1.0
)
entities.append(entity5)

entity6 = create_entity(
    annotation_id=annotation.id,
    text="500mg",
    entity_type=EntityType.DOSAGE,
    start_char=191,
    end_char=196,
    confidence=1.0
)
entities.append(entity6)

entity7 = create_entity(
    annotation_id=annotation.id,
    text="albuterol",
    entity_type=EntityType.MEDICATION,
    start_char=218,
    end_char=227,
    confidence=1.0
)
entities.append(entity7)

print(f"\nCreated {len(entities)} entities")

2025-11-06 07:21:36,790 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,792 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,793 INFO sqlalchemy.engine.Engine [generated in 0.00085s] ('dry cough', 'SYMPTOM', 29, 38, 1.0, 1, '2025-11-05 21:21:36.790581', '2025-11-05 21:21:36.790594')
2025-11-06 07:21:36,794 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,797 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,799 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,800 INFO sqlalchemy.engine.Engine [generated in 0.00077s] (1,)
✅ Entity created: ID=1, Text='dry cough', Type=symptom
2025-11-06 07:21:36,801 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,802 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,802 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,803 INFO sqlalchemy.engine.Engine [cached since 0.0112s ago] ('fever', 'SYMPTOM', 70, 75, 1.0, 1, '2025-11-05 21:21:36.801769', '2025-11-05 21:21:36.801782')
2025-11-06 07:21:36,805 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,808 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,809 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,810 INFO sqlalchemy.engine.Engine [cached since 0.01091s ago] (2,)
✅ Entity created: ID=2, Text='fever', Type=symptom
2025-11-06 07:21:36,811 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,812 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,813 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,813 INFO sqlalchemy.engine.Engine [cached since 0.02158s ago] ('shortness of breath', 'SYMPTOM', 80, 99, 1.0, 1, '2025-11-05 21:21:36.812274', '2025-11-05 21:21:36.812290')
2025-11-06 07:21:36,815 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,818 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,819 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,820 INFO sqlalchemy.engine.Engine [cached since 0.02073s ago] (3,)
✅ Entity created: ID=3, Text='shortness of breath', Type=symptom
2025-11-06 07:21:36,821 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,822 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,823 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,824 INFO sqlalchemy.engine.Engine [cached since 0.03169s ago] ('pneumonia', 'DISEASE', 155, 164, 0.95, 1, '2025-11-05 21:21:36.822261', '2025-11-05 21:21:36.822273')
2025-11-06 07:21:36,825 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,828 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,829 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,829 INFO sqlalchemy.engine.Engine [cached since 0.03061s ago] (4,)
✅ Entity created: ID=4, Text='pneumonia', Type=disease
2025-11-06 07:21:36,831 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,832 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,833 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,833 INFO sqlalchemy.engine.Engine [cached since 0.04152s ago] ('azithromycin', 'MEDICATION', 178, 190, 1.0, 1, '2025-11-05 21:21:36.832073', '2025-11-05 21:21:36.832086')
2025-11-06 07:21:36,835 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,838 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,838 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,839 INFO sqlalchemy.engine.Engine [cached since 0.04001s ago] (5,)
✅ Entity created: ID=5, Text='azithromycin', Type=medication
2025-11-06 07:21:36,840 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,841 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,842 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,843 INFO sqlalchemy.engine.Engine [cached since 0.05074s ago] ('500mg', 'DOSAGE', 191, 196, 1.0, 1, '2025-11-05 21:21:36.841404', '2025-11-05 21:21:36.841416')
2025-11-06 07:21:36,844 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,850 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,852 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,853 INFO sqlalchemy.engine.Engine [cached since 0.05421s ago] (6,)
✅ Entity created: ID=6, Text='500mg', Type=dosage
2025-11-06 07:21:36,855 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,857 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,858 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,859 INFO sqlalchemy.engine.Engine [cached since 0.06727s ago] ('albuterol', 'MEDICATION', 218, 227, 1.0, 1, '2025-11-05 21:21:36.857033', '2025-11-05 21:21:36.857049')
2025-11-06 07:21:36,861 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,865 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,866 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:36,867 INFO sqlalchemy.engine.Engine [cached since 0.068s ago] (7,)
✅ Entity created: ID=7, Text='albuterol', Type=medication
2025-11-06 07:21:36,868 INFO sqlalchemy.engine.Engine ROLLBACK

Created 7 entities

In [12]:
# Create relations between entities
# Entity IDs: 1=dry cough, 2=fever, 3=shortness of breath, 4=pneumonia, 5=azithromycin, 6=500mg, 7=albuterol

print("Creating relations between entities...\n")

# Symptoms indicate pneumonia
rel1 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity1.id,  # dry cough
    target_entity_id=entity4.id,  # pneumonia
    relation_type=RelationType.INDICATES,
    confidence=0.9
)

rel2 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity2.id,  # fever
    target_entity_id=entity4.id,  # pneumonia
    relation_type=RelationType.INDICATES,
    confidence=0.95
)

rel3 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity3.id,  # shortness of breath
    target_entity_id=entity4.id,  # pneumonia
    relation_type=RelationType.INDICATES,
    confidence=0.95
)

# Medications treat pneumonia
rel4 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity5.id,  # azithromycin
    target_entity_id=entity4.id,  # pneumonia
    relation_type=RelationType.TREATS,
    confidence=1.0
)

rel5 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity7.id,  # albuterol
    target_entity_id=entity4.id,  # pneumonia
    relation_type=RelationType.TREATS,
    confidence=0.85
)

# Dosage for medication
rel6 = create_relation(
    annotation_id=annotation.id,
    source_entity_id=entity6.id,  # 500mg
    target_entity_id=entity5.id,  # azithromycin
    relation_type=RelationType.DOSAGE_FOR,
    confidence=1.0
)

print("\n✅ All relations created successfully!")

Creating relations between entities...

2025-11-06 07:21:36,877 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,879 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,880 INFO sqlalchemy.engine.Engine [generated in 0.00123s] ('INDICATES', 1, 4, 0.9, 1, '2025-11-05 21:21:36.877223', '2025-11-05 21:21:36.877255')
2025-11-06 07:21:36,882 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,885 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,887 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,888 INFO sqlalchemy.engine.Engine [generated in 0.00085s] (1,)
✅ Relation created: ID=1, 1 --[indicates]--> 4
2025-11-06 07:21:36,889 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,890 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,891 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,892 INFO sqlalchemy.engine.Engine [cached since 0.01284s ago] ('INDICATES', 2, 4, 0.95, 1, '2025-11-05 21:21:36.890638', '2025-11-05 21:21:36.890651')
2025-11-06 07:21:36,893 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,896 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,897 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,897 INFO sqlalchemy.engine.Engine [cached since 0.0105s ago] (2,)
✅ Relation created: ID=2, 2 --[indicates]--> 4
2025-11-06 07:21:36,898 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,899 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,900 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,900 INFO sqlalchemy.engine.Engine [cached since 0.02164s ago] ('INDICATES', 3, 4, 0.95, 1, '2025-11-05 21:21:36.899473', '2025-11-05 21:21:36.899485')
2025-11-06 07:21:36,902 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,905 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,906 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,907 INFO sqlalchemy.engine.Engine [cached since 0.01967s ago] (3,)
✅ Relation created: ID=3, 3 --[indicates]--> 4
2025-11-06 07:21:36,908 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,909 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,910 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,910 INFO sqlalchemy.engine.Engine [cached since 0.03159s ago] ('TREATS', 5, 4, 1.0, 1, '2025-11-05 21:21:36.908966', '2025-11-05 21:21:36.908983')
2025-11-06 07:21:36,912 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,915 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,916 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,916 INFO sqlalchemy.engine.Engine [cached since 0.02937s ago] (4,)
✅ Relation created: ID=4, 5 --[treats]--> 4
2025-11-06 07:21:36,917 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,918 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,919 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,920 INFO sqlalchemy.engine.Engine [cached since 0.04152s ago] ('TREATS', 7, 4, 0.85, 1, '2025-11-05 21:21:36.918671', '2025-11-05 21:21:36.918686')
2025-11-06 07:21:36,922 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,925 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,926 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,926 INFO sqlalchemy.engine.Engine [cached since 0.03944s ago] (5,)
✅ Relation created: ID=5, 7 --[treats]--> 4
2025-11-06 07:21:36,928 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:36,929 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,930 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:36,930 INFO sqlalchemy.engine.Engine [cached since 0.05164s ago] ('DOSAGE_FOR', 6, 5, 1.0, 1, '2025-11-05 21:21:36.928870', '2025-11-05 21:21:36.928887')
2025-11-06 07:21:36,932 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,935 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,936 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:36,937 INFO sqlalchemy.engine.Engine [cached since 0.05034s ago] (6,)
✅ Relation created: ID=6, 6 --[dosage_for]--> 5
2025-11-06 07:21:36,939 INFO sqlalchemy.engine.Engine ROLLBACK

✅ All relations created successfully!

In [13]:
# View the entities we created
print("\n📋 Entities in this annotation:")
df_entities = list_entities(annotation_id=annotation.id)
display(df_entities)

📋 Entities in this annotation:
2025-11-06 07:21:36,945 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,947 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.annotation_id = ?
2025-11-06 07:21:36,948 INFO sqlalchemy.engine.Engine [generated in 0.00092s] (1,)
2025-11-06 07:21:36,953 INFO sqlalchemy.engine.Engine ROLLBACK

   ID                 Text        Type  Start  End  Confidence  Annotation ID
0   1            dry cough     symptom     29   38        1.00              1
1   2                fever     symptom     70   75        1.00              1
2   3  shortness of breath     symptom     80   99        1.00              1
3   4            pneumonia     disease    155  164        0.95              1
4   5         azithromycin  medication    178  190        1.00              1
5   6                500mg      dosage    191  196        1.00              1
6   7            albuterol  medication    218  227        1.00              1

In [14]:
# View the relations we created
print("\n🔗 Relations in this annotation:")
df_relations = list_relations(annotation_id=annotation.id)
display(df_relations)

🔗 Relations in this annotation:
2025-11-06 07:21:36,978 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,979 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.annotation_id = ?
2025-11-06 07:21:36,979 INFO sqlalchemy.engine.Engine [generated in 0.00057s] (1,)
2025-11-06 07:21:36,982 INFO sqlalchemy.engine.Engine ROLLBACK

,ID,Source Entity ID,Relation Type,Target Entity ID,Confidence,Annotation ID
0,1,1,indicates,4,0.90,1
1,2,2,indicates,4,0.95,1
2,3,3,indicates,4,0.95,1
3,4,5,treats,4,1.00,1
4,5,7,treats,4,0.85,1
5,6,6,dosage_for,5,1.00,1

## Example 2: Create Another Document

Let's create another sample document with its own annotations.

In [15]:
# Create second document
sample_text_2 = """Patient with type 2 diabetes mellitus diagnosed 5 years ago.
Current medications include metformin 1000mg twice daily and glipizide 10mg once daily.
Recent HbA1c results show 7.8%, indicating suboptimal glycemic control.
Patient reports occasional episodes of dizziness and fatigue."""

doc2 = create_document(
    title="Case 2: Diabetes Management",
    text=sample_text_2
)

print(f"\nDocument ID: {doc2.id}")

2025-11-06 07:21:36,992 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:36,993 INFO sqlalchemy.engine.Engine INSERT INTO documents (title, text, created_at, updated_at) VALUES (?, ?, ?, ?)
2025-11-06 07:21:36,994 INFO sqlalchemy.engine.Engine [cached since 0.2453s ago] ('Case 2: Diabetes Management', 'Patient with type 2 diabetes mellitus diagnosed 5 years ago. \nCurrent medications include metformin 1000mg twice daily and glipizide 10mg once daily. \nRecent HbA1c results show 7.8%, indicating suboptimal glycemic control. \nPatient reports occasional episodes of dizziness and fatigue.', '2025-11-05 21:21:36.992400', '2025-11-05 21:21:36.992412')
2025-11-06 07:21:36,996 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:36,999 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,000 INFO sqlalchemy.engine.Engine SELECT documents.id, documents.title, documents.text, documents.created_at, documents.updated_at
FROM documents
WHERE documents.id = ?
2025-11-06 07:21:37,001 INFO sqlalchemy.engine.Engine [cached since 0.2432s ago] (2,)
✅ Document created: ID=2, Title='Case 2: Diabetes Management'
2025-11-06 07:21:37,002 INFO sqlalchemy.engine.Engine ROLLBACK

Document ID: 2

In [16]:
# Create annotation for second document
annotation2 = create_annotation(
    document_id=doc2.id,
    annotator_id="doctor_johnson",
    status="in_progress"
)

print(f"\nAnnotation ID: {annotation2.id}")

2025-11-06 07:21:37,009 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,010 INFO sqlalchemy.engine.Engine INSERT INTO annotations (annotator_id, status, document_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
2025-11-06 07:21:37,011 INFO sqlalchemy.engine.Engine [cached since 0.2441s ago] ('doctor_johnson', 'IN_PROGRESS', 2, '2025-11-05 21:21:37.008927', '2025-11-05 21:21:37.008943')
2025-11-06 07:21:37,012 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,015 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,016 INFO sqlalchemy.engine.Engine SELECT annotations.id, annotations.annotator_id, annotations.status, annotations.document_id, annotations.created_at, annotations.updated_at
FROM annotations
WHERE annotations.id = ?
2025-11-06 07:21:37,017 INFO sqlalchemy.engine.Engine [cached since 0.2431s ago] (2,)
✅ Annotation created: ID=2, Document=2, Status=in_progress
2025-11-06 07:21:37,018 INFO sqlalchemy.engine.Engine ROLLBACK

Annotation ID: 2

In [17]:
# Add entities to second annotation
text2 = sample_text_2

# Disease
e1 = create_entity(
    annotation_id=annotation2.id,
    text="type 2 diabetes mellitus",
    entity_type=EntityType.DISEASE,
    start_char=16,
    end_char=39,
    confidence=1.0
)

# Medications
e2 = create_entity(
    annotation_id=annotation2.id,
    text="metformin",
    entity_type=EntityType.MEDICATION,
    start_char=104,
    end_char=113,
    confidence=1.0
)

e3 = create_entity(
    annotation_id=annotation2.id,
    text="1000mg",
    entity_type=EntityType.DOSAGE,
    start_char=114,
    end_char=120,
    confidence=1.0
)

e4 = create_entity(
    annotation_id=annotation2.id,
    text="glipizide",
    entity_type=EntityType.MEDICATION,
    start_char=142,
    end_char=151,
    confidence=1.0
)

e5 = create_entity(
    annotation_id=annotation2.id,
    text="10mg",
    entity_type=EntityType.DOSAGE,
    start_char=152,
    end_char=156,
    confidence=1.0
)

# Lab value
e6 = create_entity(
    annotation_id=annotation2.id,
    text="HbA1c",
    entity_type=EntityType.LAB_VALUE,
    start_char=185,
    end_char=190,
    confidence=1.0
)

# Symptoms
e7 = create_entity(
    annotation_id=annotation2.id,
    text="dizziness",
    entity_type=EntityType.SYMPTOM,
    start_char=230,
    end_char=239,
    confidence=0.95
)

e8 = create_entity(
    annotation_id=annotation2.id,
    text="fatigue",
    entity_type=EntityType.SYMPTOM,
    start_char=244,
    end_char=251,
    confidence=0.95
)

print("\n✅ Entities created for second annotation")

2025-11-06 07:21:37,027 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,028 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,029 INFO sqlalchemy.engine.Engine [cached since 0.2368s ago] ('type 2 diabetes mellitus', 'DISEASE', 16, 39, 1.0, 2, '2025-11-05 21:21:37.027168', '2025-11-05 21:21:37.027179')
2025-11-06 07:21:37,030 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,033 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,034 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,035 INFO sqlalchemy.engine.Engine [cached since 0.2364s ago] (8,)
✅ Entity created: ID=8, Text='type 2 diabetes mellitus', Type=disease
2025-11-06 07:21:37,037 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,038 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,039 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,040 INFO sqlalchemy.engine.Engine [cached since 0.2477s ago] ('metformin', 'MEDICATION', 104, 113, 1.0, 2, '2025-11-05 21:21:37.038090', '2025-11-05 21:21:37.038107')
2025-11-06 07:21:37,041 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,044 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,045 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,046 INFO sqlalchemy.engine.Engine [cached since 0.2467s ago] (9,)
✅ Entity created: ID=9, Text='metformin', Type=medication
2025-11-06 07:21:37,047 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,048 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,049 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,050 INFO sqlalchemy.engine.Engine [cached since 0.2577s ago] ('1000mg', 'DOSAGE', 114, 120, 1.0, 2, '2025-11-05 21:21:37.048125', '2025-11-05 21:21:37.048142')
2025-11-06 07:21:37,051 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,054 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,055 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,056 INFO sqlalchemy.engine.Engine [cached since 0.2568s ago] (10,)
✅ Entity created: ID=10, Text='1000mg', Type=dosage
2025-11-06 07:21:37,057 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,058 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,059 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,059 INFO sqlalchemy.engine.Engine [cached since 0.2672s ago] ('glipizide', 'MEDICATION', 142, 151, 1.0, 2, '2025-11-05 21:21:37.058158', '2025-11-05 21:21:37.058170')
2025-11-06 07:21:37,061 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,064 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,065 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,065 INFO sqlalchemy.engine.Engine [cached since 0.2666s ago] (11,)
✅ Entity created: ID=11, Text='glipizide', Type=medication
2025-11-06 07:21:37,067 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,068 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,069 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,072 INFO sqlalchemy.engine.Engine [cached since 0.28s ago] ('10mg', 'DOSAGE', 152, 156, 1.0, 2, '2025-11-05 21:21:37.068145', '2025-11-05 21:21:37.068156')
2025-11-06 07:21:37,074 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,077 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,077 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,078 INFO sqlalchemy.engine.Engine [cached since 0.2794s ago] (12,)
✅ Entity created: ID=12, Text='10mg', Type=dosage
2025-11-06 07:21:37,080 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,081 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,081 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,082 INFO sqlalchemy.engine.Engine [cached since 0.2899s ago] ('HbA1c', 'LAB_VALUE', 185, 190, 1.0, 2, '2025-11-05 21:21:37.080711', '2025-11-05 21:21:37.080724')
2025-11-06 07:21:37,083 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,086 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,087 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,088 INFO sqlalchemy.engine.Engine [cached since 0.289s ago] (13,)
✅ Entity created: ID=13, Text='HbA1c', Type=lab_value
2025-11-06 07:21:37,089 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,090 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,091 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,091 INFO sqlalchemy.engine.Engine [cached since 0.2995s ago] ('dizziness', 'SYMPTOM', 230, 239, 0.95, 2, '2025-11-05 21:21:37.090324', '2025-11-05 21:21:37.090337')
2025-11-06 07:21:37,093 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,096 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,097 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,098 INFO sqlalchemy.engine.Engine [cached since 0.2992s ago] (14,)
✅ Entity created: ID=14, Text='dizziness', Type=symptom
2025-11-06 07:21:37,099 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,100 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,101 INFO sqlalchemy.engine.Engine INSERT INTO entities (text, entity_type, start_char, end_char, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,102 INFO sqlalchemy.engine.Engine [cached since 0.3101s ago] ('fatigue', 'SYMPTOM', 244, 251, 0.95, 2, '2025-11-05 21:21:37.100556', '2025-11-05 21:21:37.100574')
2025-11-06 07:21:37,104 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,106 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,107 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
WHERE entities.id = ?
2025-11-06 07:21:37,108 INFO sqlalchemy.engine.Engine [cached since 0.3091s ago] (15,)
✅ Entity created: ID=15, Text='fatigue', Type=symptom
2025-11-06 07:21:37,109 INFO sqlalchemy.engine.Engine ROLLBACK

✅ Entities created for second annotation

In [18]:
# Add relations for second annotation
# Medications treat disease
create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e2.id,  # metformin
    target_entity_id=e1.id,  # type 2 diabetes
    relation_type=RelationType.TREATS,
    confidence=1.0
)

create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e4.id,  # glipizide
    target_entity_id=e1.id,  # type 2 diabetes
    relation_type=RelationType.TREATS,
    confidence=1.0
)

# Dosages for medications
create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e3.id,  # 1000mg
    target_entity_id=e2.id,  # metformin
    relation_type=RelationType.DOSAGE_FOR,
    confidence=1.0
)

create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e5.id,  # 10mg
    target_entity_id=e4.id,  # glipizide
    relation_type=RelationType.DOSAGE_FOR,
    confidence=1.0
)

# Symptoms caused by disease
create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e1.id,  # type 2 diabetes
    target_entity_id=e7.id,  # dizziness
    relation_type=RelationType.HAS_SYMPTOM,
    confidence=0.8
)

create_relation(
    annotation_id=annotation2.id,
    source_entity_id=e1.id,  # type 2 diabetes
    target_entity_id=e8.id,  # fatigue
    relation_type=RelationType.HAS_SYMPTOM,
    confidence=0.85
)

print("\n✅ Relations created for second annotation")

2025-11-06 07:21:37,116 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,117 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,117 INFO sqlalchemy.engine.Engine [cached since 0.2386s ago] ('TREATS', 9, 8, 1.0, 2, '2025-11-05 21:21:37.115841', '2025-11-05 21:21:37.115853')
2025-11-06 07:21:37,119 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,122 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,123 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,124 INFO sqlalchemy.engine.Engine [cached since 0.2367s ago] (7,)
✅ Relation created: ID=7, 9 --[treats]--> 8
2025-11-06 07:21:37,125 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,126 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,127 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,128 INFO sqlalchemy.engine.Engine [cached since 0.2489s ago] ('TREATS', 11, 8, 1.0, 2, '2025-11-05 21:21:37.126321', '2025-11-05 21:21:37.126339')
2025-11-06 07:21:37,129 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,132 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,133 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,133 INFO sqlalchemy.engine.Engine [cached since 0.2463s ago] (8,)
✅ Relation created: ID=8, 11 --[treats]--> 8
2025-11-06 07:21:37,134 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,135 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,136 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,137 INFO sqlalchemy.engine.Engine [cached since 0.2582s ago] ('DOSAGE_FOR', 10, 9, 1.0, 2, '2025-11-05 21:21:37.135543', '2025-11-05 21:21:37.135562')
2025-11-06 07:21:37,139 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,143 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,144 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,145 INFO sqlalchemy.engine.Engine [cached since 0.2577s ago] (9,)
✅ Relation created: ID=9, 10 --[dosage_for]--> 9
2025-11-06 07:21:37,146 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,147 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,148 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,148 INFO sqlalchemy.engine.Engine [cached since 0.2696s ago] ('DOSAGE_FOR', 12, 11, 1.0, 2, '2025-11-05 21:21:37.147242', '2025-11-05 21:21:37.147254')
2025-11-06 07:21:37,150 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,154 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,155 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,155 INFO sqlalchemy.engine.Engine [cached since 0.2683s ago] (10,)
✅ Relation created: ID=10, 12 --[dosage_for]--> 11
2025-11-06 07:21:37,156 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,157 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,158 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,159 INFO sqlalchemy.engine.Engine [cached since 0.28s ago] ('HAS_SYMPTOM', 8, 14, 0.8, 2, '2025-11-05 21:21:37.157547', '2025-11-05 21:21:37.157565')
2025-11-06 07:21:37,160 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,164 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,165 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,165 INFO sqlalchemy.engine.Engine [cached since 0.2783s ago] (11,)
✅ Relation created: ID=11, 8 --[has_symptom]--> 14
2025-11-06 07:21:37,166 INFO sqlalchemy.engine.Engine ROLLBACK
2025-11-06 07:21:37,167 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,168 INFO sqlalchemy.engine.Engine INSERT INTO relations (relation_type, source_entity_id, target_entity_id, confidence, annotation_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
2025-11-06 07:21:37,168 INFO sqlalchemy.engine.Engine [cached since 0.2898s ago] ('HAS_SYMPTOM', 8, 15, 0.85, 2, '2025-11-05 21:21:37.167432', '2025-11-05 21:21:37.167443')
2025-11-06 07:21:37,170 INFO sqlalchemy.engine.Engine COMMIT
2025-11-06 07:21:37,173 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,174 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
WHERE relations.id = ?
2025-11-06 07:21:37,175 INFO sqlalchemy.engine.Engine [cached since 0.2877s ago] (12,)
✅ Relation created: ID=12, 8 --[has_symptom]--> 15
2025-11-06 07:21:37,176 INFO sqlalchemy.engine.Engine ROLLBACK

✅ Relations created for second annotation

## View Complete Database

In [19]:
# Print overall summary
database_summary()

2025-11-06 07:21:37,181 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,181 INFO sqlalchemy.engine.Engine SELECT documents.id, documents.title, documents.text, documents.created_at, documents.updated_at
FROM documents
2025-11-06 07:21:37,182 INFO sqlalchemy.engine.Engine [cached since 0.4505s ago] ()
2025-11-06 07:21:37,183 INFO sqlalchemy.engine.Engine SELECT annotations.id, annotations.annotator_id, annotations.status, annotations.document_id, annotations.created_at, annotations.updated_at
FROM annotations
2025-11-06 07:21:37,183 INFO sqlalchemy.engine.Engine [cached since 0.4495s ago] ()
2025-11-06 07:21:37,184 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
2025-11-06 07:21:37,185 INFO sqlalchemy.engine.Engine [cached since 0.4482s ago] ()
2025-11-06 07:21:37,186 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
2025-11-06 07:21:37,187 INFO sqlalchemy.engine.Engine [cached since 0.4474s ago] ()

==================================================
📊 DATABASE SUMMARY
==================================================
📄 Documents:   2
📝 Annotations: 2
🏷️  Entities:    15
🔗 Relations:   12
==================================================

2025-11-06 07:21:37,189 INFO sqlalchemy.engine.Engine ROLLBACK

In [20]:
# View all documents
print("\n📄 ALL DOCUMENTS:")
df_docs = list_documents()
display(df_docs)

📄 ALL DOCUMENTS:
2025-11-06 07:21:37,193 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,194 INFO sqlalchemy.engine.Engine SELECT documents.id, documents.title, documents.text, documents.created_at, documents.updated_at
FROM documents
2025-11-06 07:21:37,195 INFO sqlalchemy.engine.Engine [cached since 0.4633s ago] ()
2025-11-06 07:21:37,196 INFO sqlalchemy.engine.Engine ROLLBACK

,ID,Title,Text Preview,Text Length,Created
0,1,Case 1: Respiratory Infection,Patient presents with persistent dry cough for...,306,2025-11-05T21:21:36.746874
1,2,Case 2: Diabetes Management,Patient with type 2 diabetes mellitus diagnose...,285,2025-11-05T21:21:36.992400

In [21]:
# View all annotations
print("\n📝 ALL ANNOTATIONS:")
df_anns = list_annotations()
display(df_anns)

📝 ALL ANNOTATIONS:
2025-11-06 07:21:37,204 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,205 INFO sqlalchemy.engine.Engine SELECT annotations.id, annotations.annotator_id, annotations.status, annotations.document_id, annotations.created_at, annotations.updated_at
FROM annotations
2025-11-06 07:21:37,206 INFO sqlalchemy.engine.Engine [cached since 0.4719s ago] ()
2025-11-06 07:21:37,208 INFO sqlalchemy.engine.Engine SELECT entities.id AS entities_id, entities.text AS entities_text, entities.entity_type AS entities_entity_type, entities.start_char AS entities_start_char, entities.end_char AS entities_end_char, entities.confidence AS entities_confidence, entities.annotation_id AS entities_annotation_id, entities.created_at AS entities_created_at, entities.updated_at AS entities_updated_at
FROM entities
WHERE ? = entities.annotation_id
2025-11-06 07:21:37,209 INFO sqlalchemy.engine.Engine [generated in 0.00070s] (1,)
2025-11-06 07:21:37,211 INFO sqlalchemy.engine.Engine SELECT relations.id AS relations_id, relations.relation_type AS relations_relation_type, relations.source_entity_id AS relations_source_entity_id, relations.target_entity_id AS relations_target_entity_id, relations.confidence AS relations_confidence, relations.annotation_id AS relations_annotation_id, relations.created_at AS relations_created_at, relations.updated_at AS relations_updated_at
FROM relations
WHERE ? = relations.annotation_id
2025-11-06 07:21:37,212 INFO sqlalchemy.engine.Engine [generated in 0.00065s] (1,)
2025-11-06 07:21:37,213 INFO sqlalchemy.engine.Engine SELECT entities.id AS entities_id, entities.text AS entities_text, entities.entity_type AS entities_entity_type, entities.start_char AS entities_start_char, entities.end_char AS entities_end_char, entities.confidence AS entities_confidence, entities.annotation_id AS entities_annotation_id, entities.created_at AS entities_created_at, entities.updated_at AS entities_updated_at
FROM entities
WHERE ? = entities.annotation_id
2025-11-06 07:21:37,213 INFO sqlalchemy.engine.Engine [cached since 0.005256s ago] (2,)
2025-11-06 07:21:37,214 INFO sqlalchemy.engine.Engine SELECT relations.id AS relations_id, relations.relation_type AS relations_relation_type, relations.source_entity_id AS relations_source_entity_id, relations.target_entity_id AS relations_target_entity_id, relations.confidence AS relations_confidence, relations.annotation_id AS relations_annotation_id, relations.created_at AS relations_created_at, relations.updated_at AS relations_updated_at
FROM relations
WHERE ? = relations.annotation_id
2025-11-06 07:21:37,215 INFO sqlalchemy.engine.Engine [cached since 0.00406s ago] (2,)
2025-11-06 07:21:37,216 INFO sqlalchemy.engine.Engine ROLLBACK

,ID,Document ID,Annotator,Status,Entities,Relations,Updated
0,1,1,doctor_smith,in_progress,7,6,2025-11-05T21:21:36.765203
1,2,2,doctor_johnson,in_progress,8,6,2025-11-05T21:21:37.008943

In [22]:
# View all entities
print("\n🏷️  ALL ENTITIES:")
df_ents = list_entities()
display(df_ents)

🏷️  ALL ENTITIES:
2025-11-06 07:21:37,226 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,227 INFO sqlalchemy.engine.Engine SELECT entities.id, entities.text, entities.entity_type, entities.start_char, entities.end_char, entities.confidence, entities.annotation_id, entities.created_at, entities.updated_at
FROM entities
2025-11-06 07:21:37,227 INFO sqlalchemy.engine.Engine [cached since 0.4904s ago] ()
2025-11-06 07:21:37,229 INFO sqlalchemy.engine.Engine ROLLBACK

,ID,Text,Type,Start,End,Confidence,Annotation ID
0,1,dry cough,symptom,29,38,1.00,1
1,2,fever,symptom,70,75,1.00,1
2,3,shortness of breath,symptom,80,99,1.00,1
3,4,pneumonia,disease,155,164,0.95,1
4,5,azithromycin,medication,178,190,1.00,1
5,6,500mg,dosage,191,196,1.00,1
6,7,albuterol,medication,218,227,1.00,1
7,8,type 2 diabetes mellitus,disease,16,39,1.00,2
8,9,metformin,medication,104,113,1.00,2
9,10,1000mg,dosage,114,120,1.00,2
10,11,glipizide,medication,142,151,1.00,2
11,12,10mg,dosage,152,156,1.00,2
12,13,HbA1c,lab_value,185,190,1.00,2
13,14,dizziness,symptom,230,239,0.95,2
14,15,fatigue,symptom,244,251,0.95,2

In [23]:
# View all relations
print("\n🔗 ALL RELATIONS:")
df_rels = list_relations()
display(df_rels)

🔗 ALL RELATIONS:
2025-11-06 07:21:37,241 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-11-06 07:21:37,241 INFO sqlalchemy.engine.Engine SELECT relations.id, relations.relation_type, relations.source_entity_id, relations.target_entity_id, relations.confidence, relations.annotation_id, relations.created_at, relations.updated_at
FROM relations
2025-11-06 07:21:37,242 INFO sqlalchemy.engine.Engine [cached since 0.5023s ago] ()
2025-11-06 07:21:37,244 INFO sqlalchemy.engine.Engine ROLLBACK

,ID,Source Entity ID,Relation Type,Target Entity ID,Confidence,Annotation ID
0,1,1,indicates,4,0.90,1
1,2,2,indicates,4,0.95,1
2,3,3,indicates,4,0.95,1
3,4,5,treats,4,1.00,1
4,5,7,treats,4,0.85,1
5,6,6,dosage_for,5,1.00,1
6,7,9,treats,8,1.00,2
7,8,11,treats,8,1.00,2
8,9,10,dosage_for,9,1.00,2
9,10,12,dosage_for,11,1.00,2
10,11,8,has_symptom,14,0.80,2
11,12,8,has_symptom,15,0.85,2

## Manual Population Template

Use this template to add more documents and annotations manually.

In [24]:
# TEMPLATE: Create a new document
# Uncomment and modify to create your own document

# my_text = """Your medical text here."""
#
# my_doc = create_document(
#     title="My Case Title",
#     text=my_text
# )
#
# my_annotation = create_annotation(
#     document_id=my_doc.id,
#     annotator_id="your_name",
#     status="in_progress"
# )
#
# # Add entities
# my_entity = create_entity(
#     annotation_id=my_annotation.id,
#     text="entity text",
#     entity_type=EntityType.DISEASE,  # Change to appropriate type
#     start_char=0,  # Find in text
#     end_char=5,    # Find in text
#     confidence=1.0
# )
#
# # Add relations
# my_relation = create_relation(
#     annotation_id=my_annotation.id,
#     source_entity_id=entity1.id,
#     target_entity_id=entity2.id,
#     relation_type=RelationType.TREATS,
#     confidence=1.0
# )

In [25]:
print("\n📋 ENTITY TYPES:")
print("="*50)
for entity_type in EntityType:
    print(f"  • EntityType.{entity_type.name:15} = '{entity_type.value}'")

print("\n🔗 RELATION TYPES:")
print("="*50)
for relation_type in RelationType:
    print(f"  • RelationType.{relation_type.name:20} = '{relation_type.value}'")

📋 ENTITY TYPES:
==================================================
  • EntityType.DISEASE         = 'disease'
  • EntityType.MEDICATION      = 'medication'
  • EntityType.SYMPTOM         = 'symptom'
  • EntityType.PROCEDURE       = 'procedure'
  • EntityType.ANATOMY         = 'anatomy'
  • EntityType.LAB_VALUE       = 'lab_value'
  • EntityType.DOSAGE          = 'dosage'
  • EntityType.OTHER           = 'other'

🔗 RELATION TYPES:
==================================================
  • RelationType.TREATS               = 'treats'
  • RelationType.CAUSES               = 'causes'
  • RelationType.HAS_SYMPTOM          = 'has_symptom'
  • RelationType.INDICATES            = 'indicates'
  • RelationType.CONTRAINDICATES      = 'contraindicates'
  • RelationType.DOSAGE_FOR           = 'dosage_for'
  • RelationType.LOCATED_IN           = 'located_in'
  • RelationType.TEMPORAL             = 'temporal'
  • RelationType.OTHER                = 'other'